### ISSUE TITLE
Doesn't open folder

### ISSUE THREAD

**Issue by jmfergeau** [Dogeek/renpy-text-editor#20]
I managed to make it run but when I open the `game` folder that contains the rpy files, nothing appears in the list.

That's too bad, with VSCode refusing to set itself up and Atom crashing, i was really needing a dedicated editor for renpy... :/

**Comment by sbordeyne** [comment]
Hello,

I haven't worked on this project for literally years, and I don't plan on maintaining it any longer. VS Code is more feature-complete at this point, and the functionality added by this app should just be a Ren'Py extension for VS Code. I'll eventually get around to making such an extension I think, but it's not in my immediate plans to do so.
